# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_MACH_EXYNOS9810_R7_GLOBAL) := \
    exynos/exynos9810.dtb

dtbo-$(CONFIG_MACH_EXYNOS9810_R7_GLOBAL) := \
    samsung/exynos9810-r7_eur_open_00.dtbo \
    samsung/exynos9810-r7_eur_open_01.dtbo \
    samsung/exynos9810-r7_eur_open_02.dtbo \
    samsung/exynos9810-r7_eur_open_03.dtbo \
    samsung/exynos9810-r7_eur_open_04.dtbo \
    samsung/exynos9810-r7_eur_open_05.dtbo

always         := $(dtb-y) $(dtbo-y)
clean-files    := *.dtb *.dtbo
